import hashlib
import hmac
import os
import math
import random
from bitarray import bitarray
from cryptography.hazmat.primitives.ciphers.aead import AESGCM SIV
from cryptography.hazmat.backends import default_backend


class H1:
    """Collision-resistant hash function H₁ (binds verify point, ID ciphertext, and epoch index)."""
    def __init__(self, key: bytes):
        self.key = key  # HMAC key (generated by RA in Setup)

    def eval(self, vp: bytes, ci: bytes, epoch_idx: int) -> bytes:
        """
        Compute H₁(vp || Ci || i) using HMAC-SHA256.
        Args:
            vp: Verify point of the TOTP instance (bytes)
            ci: Encrypted identity (Ci from ASE, bytes)
            epoch_idx: Index of the verify epoch (i)
        Returns:
            Bound hash value (bytes)
        """
        data = vp + ci + str(epoch_idx).encode()
        return hmac.new(self.key, data, hashlib.sha256).digest()